FROM nvcr.io/nvidia/cuda:11.6.0-devel-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN echo "Installing apt packages..." \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends \
       build-essential \
       python3 \
       python3-dev \
       python3-pip \
       git \
       wget \
       libeigen3-dev \
       sudo \
       vim \
       iputils-ping \
       net-tools \
       dos2unix \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && export DEBIAN_FRONTEND=dialog



# Setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# Setup environment
RUN apt-get update
RUN apt-get upgrade -y --no-install-recommends
RUN DEBIAN_FRONTEND=noninteractive

# Install basics
RUN apt-get update -y \
    && apt-get install build-essential \
    && apt-get install -y apt-utils git curl ca-certificates bzip2 tree htop wget \
    && apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev bmon iotop g++ python3.8 python3.8-dev python3.8-distutils

# Install python
RUN ln -sv /usr/bin/python3.8 /usr/bin/python
RUN ln -svf /usr/bin/python3.8 /usr/bin/python3
RUN alias python3=python3.8
RUN wget https://bootstrap.pypa.io/get-pip.py && \
	python get-pip.py && python3 get-pip.py && \
	rm get-pip.py

# Install python packages
COPY ./requirements.txt ./
RUN python3 -m pip install -r /requirements.txt

# Install ROS Noetic
ENV ROS_DISTRO noetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update && apt-get install -y ros-$ROS_DISTRO-desktop-full && \
    apt-get install -y python3-rosdep && \
    rosdep init && \
    rosdep update && \
    apt-get install -y ros-$ROS_DISTRO-rospy

# Install ROS packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-rosdep \
    python3-rosinstall \
    python3-rosinstall-generator \
    python3-wstool \
    build-essential \
    python3-catkin-tools \
    ros-noetic-catkin \
    ros-noetic-robot-state-publisher \
    ros-noetic-moveit \
    ros-noetic-rosbridge-suite \
    ros-noetic-joy \
    ros-noetic-ros-control \
    ros-noetic-ros-controllers \
    ros-noetic-tf2-web-republisher
    
# Append the ROS source command to the root user's .bashrc
# RUN echo "source /volume/myhal_ws/devel/setup.bash" >> ~/.bashrc
