version: "3.8"

services:
  star:
    image: star${USER}
    build:
            context: ..
            dockerfile: ./docker/Dockerfile
    stdin_open: true
    tty: true
    ipc: host
    network_mode: host
    privileged: true
    environment:
#       NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
      # X11_SOCKET: /tmp/.X11-unix
      XAUTHORITY: /home/${USER}/.Xauthority
      # XAUTHORITY: /Users/${USER}/.Xauthority
      QT_X11_NO_MITSHM: 1
      QT_GRAPHICSSYSTEM: native   
    volumes:
      - ../:/volume
      - /tmp/.X11-unix:/tmp/.X11-unix
            - ../:/volume
    working_dir: /volume
    command: /bin/bash
#     deploy:
#             resources:
#                     reservations:
#                             devices:
#                                     - driver: nvidia
#                                       count: 1
#                                       capabilities: [gpu]

