//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSArmControlInterface
{
    [Serializable]
    public class ButtonStateMsg : Message
    {
        public const string k_RosMessageName = "ROS_Arm_Control_Interface/ButtonState";
        public override string RosMessageName => k_RosMessageName;

        public bool grab;
        public bool index;
        public bool stick;
        public bool x_input;
        public bool y_input;
        public bool stick_down;
        public bool stick_up;

        public ButtonStateMsg()
        {
            this.grab = false;
            this.index = false;
            this.stick = false;
            this.x_input = false;
            this.y_input = false;
            this.stick_down = false;
            this.stick_up = false;
        }

        public ButtonStateMsg(bool grab, bool index, bool stick, bool x_input, bool y_input, bool stick_down, bool stick_up)
        {
            this.grab = grab;
            this.index = index;
            this.stick = stick;
            this.x_input = x_input;
            this.y_input = y_input;
            this.stick_down = stick_down;
            this.stick_up = stick_up;
        }

        public static ButtonStateMsg Deserialize(MessageDeserializer deserializer) => new ButtonStateMsg(deserializer);

        private ButtonStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.grab);
            deserializer.Read(out this.index);
            deserializer.Read(out this.stick);
            deserializer.Read(out this.x_input);
            deserializer.Read(out this.y_input);
            deserializer.Read(out this.stick_down);
            deserializer.Read(out this.stick_up);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.grab);
            serializer.Write(this.index);
            serializer.Write(this.stick);
            serializer.Write(this.x_input);
            serializer.Write(this.y_input);
            serializer.Write(this.stick_down);
            serializer.Write(this.stick_up);
        }

        public override string ToString()
        {
            return "ButtonStateMsg: " +
            "\ngrab: " + grab.ToString() +
            "\nindex: " + index.ToString() +
            "\nstick: " + stick.ToString() +
            "\nx_input: " + x_input.ToString() +
            "\ny_input: " + y_input.ToString() +
            "\nstick_down: " + stick_down.ToString() +
            "\nstick_up: " + stick_up.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
