//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.ROSArmControlInterface
{
    [Serializable]
    public class ControllerInfoMsg : Message
    {
        public const string k_RosMessageName = "ROS_Arm_Control_Interface/ControllerInfo";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        //  TODO remove after webview is more developed
        public string controller_string_info;
        public PosRotMsg cc_pose_cur;
        public PosRotMsg cc_pose_init;
        public PosRotMsg ee_pose_cur;
        public PosRotMsg ee_pose_default;
        public PosRotMsg ee_pose_target;
        public float rg_pose_target;
        public JointStateMsg joint_state;
        public JointStateMsg gripper_state;
        public float[] bounding_box_params;
        public float[] position_tolerance;
        public float orientation_tolerance;
        public string control_mode;
        public string interface_mode;

        public ControllerInfoMsg()
        {
            this.header = new HeaderMsg();
            this.controller_string_info = "";
            this.cc_pose_cur = new PosRotMsg();
            this.cc_pose_init = new PosRotMsg();
            this.ee_pose_cur = new PosRotMsg();
            this.ee_pose_default = new PosRotMsg();
            this.ee_pose_target = new PosRotMsg();
            this.rg_pose_target = 0.0f;
            this.joint_state = new JointStateMsg();
            this.gripper_state = new JointStateMsg();
            this.bounding_box_params = new float[0];
            this.position_tolerance = new float[0];
            this.orientation_tolerance = 0.0f;
            this.control_mode = "";
            this.interface_mode = "";
        }

        public ControllerInfoMsg(HeaderMsg header, string controller_string_info, PosRotMsg cc_pose_cur, PosRotMsg cc_pose_init, PosRotMsg ee_pose_cur, PosRotMsg ee_pose_default, PosRotMsg ee_pose_target, float rg_pose_target, JointStateMsg joint_state, JointStateMsg gripper_state, float[] bounding_box_params, float[] position_tolerance, float orientation_tolerance, string control_mode, string interface_mode)
        {
            this.header = header;
            this.controller_string_info = controller_string_info;
            this.cc_pose_cur = cc_pose_cur;
            this.cc_pose_init = cc_pose_init;
            this.ee_pose_cur = ee_pose_cur;
            this.ee_pose_default = ee_pose_default;
            this.ee_pose_target = ee_pose_target;
            this.rg_pose_target = rg_pose_target;
            this.joint_state = joint_state;
            this.gripper_state = gripper_state;
            this.bounding_box_params = bounding_box_params;
            this.position_tolerance = position_tolerance;
            this.orientation_tolerance = orientation_tolerance;
            this.control_mode = control_mode;
            this.interface_mode = interface_mode;
        }

        public static ControllerInfoMsg Deserialize(MessageDeserializer deserializer) => new ControllerInfoMsg(deserializer);

        private ControllerInfoMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.controller_string_info);
            this.cc_pose_cur = PosRotMsg.Deserialize(deserializer);
            this.cc_pose_init = PosRotMsg.Deserialize(deserializer);
            this.ee_pose_cur = PosRotMsg.Deserialize(deserializer);
            this.ee_pose_default = PosRotMsg.Deserialize(deserializer);
            this.ee_pose_target = PosRotMsg.Deserialize(deserializer);
            deserializer.Read(out this.rg_pose_target);
            this.joint_state = JointStateMsg.Deserialize(deserializer);
            this.gripper_state = JointStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.bounding_box_params, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.position_tolerance, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.orientation_tolerance);
            deserializer.Read(out this.control_mode);
            deserializer.Read(out this.interface_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.controller_string_info);
            serializer.Write(this.cc_pose_cur);
            serializer.Write(this.cc_pose_init);
            serializer.Write(this.ee_pose_cur);
            serializer.Write(this.ee_pose_default);
            serializer.Write(this.ee_pose_target);
            serializer.Write(this.rg_pose_target);
            serializer.Write(this.joint_state);
            serializer.Write(this.gripper_state);
            serializer.WriteLength(this.bounding_box_params);
            serializer.Write(this.bounding_box_params);
            serializer.WriteLength(this.position_tolerance);
            serializer.Write(this.position_tolerance);
            serializer.Write(this.orientation_tolerance);
            serializer.Write(this.control_mode);
            serializer.Write(this.interface_mode);
        }

        public override string ToString()
        {
            return "ControllerInfoMsg: " +
            "\nheader: " + header.ToString() +
            "\ncontroller_string_info: " + controller_string_info.ToString() +
            "\ncc_pose_cur: " + cc_pose_cur.ToString() +
            "\ncc_pose_init: " + cc_pose_init.ToString() +
            "\nee_pose_cur: " + ee_pose_cur.ToString() +
            "\nee_pose_default: " + ee_pose_default.ToString() +
            "\nee_pose_target: " + ee_pose_target.ToString() +
            "\nrg_pose_target: " + rg_pose_target.ToString() +
            "\njoint_state: " + joint_state.ToString() +
            "\ngripper_state: " + gripper_state.ToString() +
            "\nbounding_box_params: " + System.String.Join(", ", bounding_box_params.ToList()) +
            "\nposition_tolerance: " + System.String.Join(", ", position_tolerance.ToList()) +
            "\norientation_tolerance: " + orientation_tolerance.ToString() +
            "\ncontrol_mode: " + control_mode.ToString() +
            "\ninterface_mode: " + interface_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
