//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSArmControlInterface
{
    [Serializable]
    public class InterfaceInfoMsg : Message
    {
        public const string k_RosMessageName = "ROS_Arm_Control_Interface/InterfaceInfo";
        public override string RosMessageName => k_RosMessageName;

        public bool ResetButton;
        public bool GrabButton;
        public bool AutomaticGrabButton;
        public float ScalingButton;

        public InterfaceInfoMsg()
        {
            this.ResetButton = false;
            this.GrabButton = false;
            this.AutomaticGrabButton = false;
            this.ScalingButton = 0.0f;
        }

        public InterfaceInfoMsg(bool ResetButton, bool GrabButton, bool AutomaticGrabButton, float ScalingButton)
        {
            this.ResetButton = ResetButton;
            this.GrabButton = GrabButton;
            this.AutomaticGrabButton = AutomaticGrabButton;
            this.ScalingButton = ScalingButton;
        }

        public static InterfaceInfoMsg Deserialize(MessageDeserializer deserializer) => new InterfaceInfoMsg(deserializer);

        private InterfaceInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ResetButton);
            deserializer.Read(out this.GrabButton);
            deserializer.Read(out this.AutomaticGrabButton);
            deserializer.Read(out this.ScalingButton);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ResetButton);
            serializer.Write(this.GrabButton);
            serializer.Write(this.AutomaticGrabButton);
            serializer.Write(this.ScalingButton);
        }

        public override string ToString()
        {
            return "InterfaceInfoMsg: " +
            "\nResetButton: " + ResetButton.ToString() +
            "\nGrabButton: " + GrabButton.ToString() +
            "\nAutomaticGrabButton: " + AutomaticGrabButton.ToString() +
            "\nScalingButton: " + ScalingButton.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
