//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSArmControlInterface
{
    [Serializable]
    public class StackEventMsg : Message
    {
        public const string k_RosMessageName = "ROS_Arm_Control_Interface/StackEvent";
        public override string RosMessageName => k_RosMessageName;

        public byte stack_status;
        //  stack_status enum values
        public const byte INITIAL = 0;
        public const byte START = 1;
        public const byte RUNNING = 2;
        public const byte EXIT = 3;

        public StackEventMsg()
        {
            this.stack_status = 0;
        }

        public StackEventMsg(byte stack_status)
        {
            this.stack_status = stack_status;
        }

        public static StackEventMsg Deserialize(MessageDeserializer deserializer) => new StackEventMsg(deserializer);

        private StackEventMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stack_status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stack_status);
        }

        public override string ToString()
        {
            return "StackEventMsg: " +
            "\nstack_status: " + stack_status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
