//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.ROSArmControlInterface
{
    [Serializable]
    public class StackInfoMsg : Message
    {
        public const string k_RosMessageName = "ROS_Arm_Control_Interface/StackInfo";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public string current_state;
        public string current_state_id;
        public string previous_state;
        public string pervious_state_id;

        public StackInfoMsg()
        {
            this.header = new HeaderMsg();
            this.current_state = "";
            this.current_state_id = "";
            this.previous_state = "";
            this.pervious_state_id = "";
        }

        public StackInfoMsg(HeaderMsg header, string current_state, string current_state_id, string previous_state, string pervious_state_id)
        {
            this.header = header;
            this.current_state = current_state;
            this.current_state_id = current_state_id;
            this.previous_state = previous_state;
            this.pervious_state_id = pervious_state_id;
        }

        public static StackInfoMsg Deserialize(MessageDeserializer deserializer) => new StackInfoMsg(deserializer);

        private StackInfoMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.current_state);
            deserializer.Read(out this.current_state_id);
            deserializer.Read(out this.previous_state);
            deserializer.Read(out this.pervious_state_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.current_state);
            serializer.Write(this.current_state_id);
            serializer.Write(this.previous_state);
            serializer.Write(this.pervious_state_id);
        }

        public override string ToString()
        {
            return "StackInfoMsg: " +
            "\nheader: " + header.ToString() +
            "\ncurrent_state: " + current_state.ToString() +
            "\ncurrent_state_id: " + current_state_id.ToString() +
            "\nprevious_state: " + previous_state.ToString() +
            "\npervious_state_id: " + pervious_state_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
