//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSArmControlInterface
{
    [Serializable]
    public class StateInfoMsg : Message
    {
        public const string k_RosMessageName = "ROS_Arm_Control_Interface/StateInfo";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string id;
        public string message;

        public StateInfoMsg()
        {
            this.name = "";
            this.id = "";
            this.message = "";
        }

        public StateInfoMsg(string name, string id, string message)
        {
            this.name = name;
            this.id = id;
            this.message = message;
        }

        public static StateInfoMsg Deserialize(MessageDeserializer deserializer) => new StateInfoMsg(deserializer);

        private StateInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.id);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.id);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "StateInfoMsg: " +
            "\nname: " + name.ToString() +
            "\nid: " + id.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
